### ISSUE TITLE
Enable Steam Comments Section

### ISSUE THREAD

**Issue by kebeb1334** [TheDogKSP/MoreEffectiveTransfer#21]
It's nice to continue a mod and keep it alive for the community, but if you're not accepting reasonable feedback you aren't doing this for the community at all. If you want all of the glory you need to accept when things need adjustment. 

Shutting down the comments section because you didn't like the feedback is childish and telling users that all the features work when they actually don't is the definition of gaslighting. 

It's hard to trust a developer who adds "**note: this mod is now feature complete and working as intended.**" to their patch notes without user testing.

**Comment by TheDogKSP** [comment]
unqualified feedback, nonsense deleted
