### ISSUE TITLE
Feature request: matchmaking healthcare/medicopters

### ISSUE THREAD

**Issue by CrankyAnt** [TheDogKSP/MoreEffectiveTransfer#7]
Hello,

Awesome mod, really glad you updated it for airports with the continuation mod. METM clearly states in its description it will optimize transferoffers for police, fire, deathcare, garbage, snow and road+park maintenance. Healthcare is mentioned in the description of the mod but its not clear what actually happens/changes. 

My issue and therefore also featurerequest has to do with medical helicopters picking up a patient somewhere in the city, these helicopters then always go to the same destination to deliver the patient; in my city this is a small clinic on the edge of town... even when its picking up a patient 1 block away from a major hospital with helicopter deck on top. 

As these medical helicopters have a flight facility to return to without patient capacity I suspect thats the reason why this happens.. they simply cannot bring the patient back so their offer has to be matched by another facility. 

Do you think this handling could be improved by the mod? and if so, do you want to considder implementing it?

Thanks in advance and compliments on continuing it!

**Comment by TheDogKSP** [comment]
Will take a look, this should be the sickmove offer type, maybe that needs to change from incoming to outgoing match mode...

**Comment by CrankyAnt** [comment]
Awesome, tnx!

**Comment by TheDogKSP** [comment]
fixed in release [2.0.5.220220] (due tomorrow)
